### ISSUE TITLE
Async Function Not Working Locally

### ISSUE THREAD

**Issue by james-ingold** [richlloydmiles/serverless-step-functions-local-example#1]
Hey there thanks for putting out this great example, I'm curious if this code still works as expected for you. With the async function handlers, it seems to stop on the first "hello" execution and hang there. I ended up having to change the handlers to non-async to get it to work. 

curl --location --request GET 'http://localhost:3000/local-dev/hello'

Should print "hello" and then "world" but hangs after "hello"

Seems to be an issue with the step functions local execution. 

```
module.exports.hello = async event => {
  console.log('hello')
  return { foo: 1 }
}
```

<img width="841" alt="Screen Shot 2021-11-10 at 2 02 10 PM" src="https://user-images.githubusercontent.com/700919/141185536-0876a2e0-34b2-48e7-895a-3a3a9627dd72.png">

**Comment by sethii** [comment]
@james-ingold not sure if you still have this problem, but I found a solution :)

The problem is in `serverless-offline-lambda`, but we don't need it anymore, because `serverless-offline` supports local invocation in newer version (which in fact is used in this example). 

In order to make it work locally we just need to follow few steps:
1. Turn off `serverless-offline-lambda` in serverless.yaml
2. We need to change mapping here, to follow the convention of `arn:aws:lambda:us-east-1:101010101010:function:<service>-<stage>-<function-name>` so in this case it should be `arn:aws:lambda:us-east-1:101010101010:function:stepfunctions-local-dev-hello`
3. We also need to add additional parameter to run serverless-offline `"start": "serverless offline start --stage local-dev --lambdaPort 4000"` - lambdaPort is a key here :) 

Those three simple steps should make it possible to run

**Comment by james-ingold** [comment]
Thanks for digging into this @sethii!
